Make codelens font follow settings
compiler-explorer/compiler-explorer pull request #2402
Opened 2021-01-26 04:57 UTC by justin-gerhardt

The default codelens font stack is proportional which gets really irritating when counting bytes.
![CE-before](https://user-images.githubusercontent.com/6844979/105802315-e188ab80-5f68-11eb-9cfd-c4ad0a42f09b.png)
I've updated it so that is follows the font stack specified in settings (which is default monospace!)
![CE-after](https://user-images.githubusercontent.com/6844979/105802376-054bf180-5f69-11eb-98da-223558ffe01b.png)

2021-01-26 05:39 UTC, apmorton commented
It does look like proper support for configuring the codelens font has landed upstream: https://github.com/microsoft/vscode/issues/16038

There is no monaco release for this yet, so I am OK landing this in the meantime as long as we add some comments in the code about the situation so we don't forget about it in the future when a monaco update happens on our end.

2021-01-26 05:42 UTC, apmorton requested changes

2021-01-26 05:42 UTC, apmorton commented on static/explorer.scss
> +
nit: please replace this extra blank line with a comment about the features yet to land in monaco: https://github.com/microsoft/vscode/issues/16038

2021-01-26 05:42 UTC, apmorton commented on static/explorer.scss
> +:root{
nit: missing space before the `{`

2021-01-26 05:42 UTC, apmorton commented on static/themes.js
> +        document.querySelector(':root').style.setProperty('--user-selected-font-stack', newSettings.editorsFFont);
nit: please duplicate comment mentioned above here

2021-01-26 17:26 UTC, apmorton approved these changes
Changes LGTM (but I haven't tried them myself)

2021-02-01 21:28 UTC, partouf commented
Tested this, and I like it. Thanks!

2021-02-01 21:29 UTC, merged

2021-02-01 21:58 UTC, partouf commented
This is now live

2021-02-01 22:13 UTC, justin-gerhardt commented
Excellent, Thank You