Report back an estimate of filtered lines
compiler-explorer/compiler-explorer pull request #2506
Opened 2021-03-19 17:24 UTC by RubenRBS

Adds an estimate of how many lines were filtered out when the result is empty (Maybe we could also add them for every compilation?)

While it's not a fix for #2505 , it implements the suggestion given there by @dkm :)

Note that I had to `--no-verify` the commit because I couldn't bless the filter tests. Also, some work needs to be done to reduce the function where most of the edits take place - It has exceeded its max length of 50, but I just added an ingnore for now

2021-03-19 17:27 UTC, dkm commented
wow, that was quick! Thanks !

2021-03-19 17:27 UTC, partouf commented
I've been fighting and refactoring because of that lint error for a very long time.

Other than that, I think I like this addition.

2021-03-19 17:31 UTC, dkm commented
Maybe the message could be changed ? As there is some assembly generated, but filtered out. Could be `No assembly generated` when nothing has been filtered and result is really empty, and `No assembly to display (~xxx lines filtered)` ? Or maybe this is enough and you can ignore this comment.

2021-03-19 22:19 UTC, partouf approved these changes

2021-03-19 22:21 UTC, partouf commented
Note; this isn't implemented in the `processBinaryAsm` function yet

2021-03-19 22:22 UTC, partouf requested changes
Needs to be implemented also in `processBinaryAsm`

2021-03-19 23:50 UTC, RubenRBS commented
Good catch. I've added the reporting to the binary mode, and simplified its implementation. Thanks for taking a look at it :)

2021-03-19 23:52 UTC, partouf commented
> Good catch. I've added the reporting to the binary mode, and simplified its implementation. Thanks for taking a look at it :)

Ah yes, much better!

2021-03-19 23:52 UTC, partouf approved these changes

2021-03-20 07:15 UTC, dkm commented
Thank you both for being so quick !

2021-03-20 19:17 UTC, merged

2021-03-20 19:35 UTC, partouf commented
This is now live!