Add Kotlin/JVM support
compiler-explorer/compiler-explorer pull request #2637
Opened 2021-05-01 18:26 UTC by DanielBelow

This adds support for Kotlin/JVM.

Info on getting a standalone Kotlin compiler can be found on [kotlinlang.org](https://kotlinlang.org/docs/command-line.html), e.g. from [Kotlin's github releases](https://github.com/JetBrains/kotlin/releases/tag/v1.4.32). 
Note not to use the `kotlin-native-*` archives, but e.g. `kotlin-compiler-1.4.32.zip`.

2021-05-01 18:37 UTC, supergrecko requested changes
Looks good. However, there are a few things we should consider changing and one thing to add.

The kotlinc/kotlinc-jvm drivers take different arguments than the Java Compiler and therefore we should filter out different arguments.

We are aiming to look at the generated bytecode from the Kotlin source file which means we should be preventing KotlinScript from running. I believe all of the following arguments should be filtered out in filterUserOptions

- -script
- -progressive
- -d
- -kotlin-home
- -jdk-home-path

2021-05-01 18:37 UTC, supergrecko commented on etc/config/kotlin.defaults.properties
> +compiler.kotlincdefault.exe=/usr/bin/kotlinc
We are not interested in allowing kotlinc-js to be invoked. The kotlinc-jvm driver should be used for this.

```suggestion
compiler.kotlincdefault.exe=/usr/bin/kotlinc-jvm
```

2021-05-01 18:37 UTC, supergrecko commented on lib/compilers/_all.js
>  export { JavaCompiler } from './java';
These exports should be alphabetically ordered

```suggestion
export { ISPCCompiler } from './ispc';
export { JavaCompiler } from './java';
export { KotlinCompiler } from './kotlin';
```

2021-05-01 20:02 UTC, DanielBelow commented
Thanks for being so quick to review:)

I've added the arguments you suggested, but I noticed there's also `-Xjavac-arguments=<options>`, to forward arguments to `javac`, so I might be able to pass options to `javac` this way, that would be filtered out by `java.js`'s `filterUserOptions`(?)

A similar flag exists for NVCC (`-Xcompiler`), but I don't see any special handling of that in `nvcc.js`.

Should we also exclude `-Xjavac-arguments`?

2021-05-03 12:06 UTC, supergrecko commented
Yes, I think we should exclude that as well. Can simply just filter anything that starts with -Xjavac

2021-05-04 18:13 UTC, RubenRBS approved these changes

2021-05-04 18:13 UTC, RubenRBS commented on lib/compilers/kotlin.js
> +// Copyright (c) 2019, Compiler Explorer Authors
Outdated copyright year
```suggestion
// Copyright (c) 2021, Compiler Explorer Authors
```

2021-05-04 20:33 UTC, partouf commented
Can you describe the installation process? Or could you write it in a similar way in which we install java for example https://github.com/compiler-explorer/infra/blob/main/bin/yaml/java.yaml

2021-05-04 20:56 UTC, DanielBelow commented
I linked to the documentation on how to install in my first comment: https://kotlinlang.org/docs/command-line.html
For a manual install:

> Unzip the standalone compiler into a directory and optionally add the bin directory to the system path. The bin directory contains the scripts needed to compile and run Kotlin on Windows, OS X and Linux.

Standalone compiler can be downloaded from the github releases: https://github.com/JetBrains/kotlin/releases/tag/v1.4.32, so the direct link to a standalone v1.4.32 version is https://github.com/JetBrains/kotlin/releases/download/v1.4.32/kotlin-compiler-1.4.32.zip

I _assume_ it could work like the java example, of course checking for `bin/kotlinc-jvm -version` instead:

```
compilers:
  kotlin:
    compression: zip
    dir: kotlin-{name}
    check_exe: bin/kotlinc-jvm -version
    targets:
      - name: 1.4.32
        url: https://github.com/JetBrains/kotlin/releases/download/v1.4.32/kotlin-compiler-1.4.32.zip
```

2021-05-04 21:06 UTC, supergrecko commented
One thing we should ensure when setting up infra for Kotlin/JVM is to make it easy for us to enable Kotlin/Native further down the road. Maybe we should prefix dir with `kotlin-jvm-{name}` assuming the dir key is where the binaries will be stored.

2021-05-07 07:15 UTC, supergrecko commented
Applying the following patch for the `kotlin.amazon.properties` seems to make it work with the compilers added in https://github.com/compiler-explorer/infra/pull/510

https://gist.github.com/supergrecko/7ff0b687d2f58c4a188a3ac1f62b8c20

2021-05-10 10:01 UTC, supergrecko approved these changes
LGTM. Tested this locally. There's definitely some filtering work to do with the javap output (such as LocalVariableTable showing up), but I aim to improve that further down the road as the current implementation is pretty hacky. 
![image](https://user-images.githubusercontent.com/42585241/117642231-5766fa80-b187-11eb-998b-aa506ce6e6ac.png)

2021-05-10 10:18 UTC, partouf commented
Something I encountered during installation and checking afterwards:
The scripts `kotlinc-jvm` and `kotlinc` require a `java` in the path or `JAVA_HOME` to be set. These are not available by default on any of our instances.

Not entirely sure what's the best option, but likely something with setting JAVA_HOME to one of the java's we have installed. For example `/opt/compiler-explorer/jdk-16.0.1`. We would either need to set this inside of CE, or on our instances.

I would think inside CE would be best, as that's more flexible and wouldn't require us to make new images of our instances.
A global JAVAHOME (or something) property would probably be fine, but per kotlin compiler would probably be best.

2021-05-10 11:30 UTC, supergrecko commented
> I would think inside CE would be best, as that's more flexible and wouldn't require us to make new images of our instances.
> A global JAVAHOME (or something) property would probably be fine, but per kotlin compiler would probably be best.

A per Kotlin compiler solution seems like the ideal solution here. Setting a global JAVA_HOME could also cause problems further down the road if we introduce other Java-based tools.

2021-05-15 15:24 UTC, DanielBelow commented
@partouf Just so I understand correctly: this would look similar to what golang is doing when looking up `goroot`, `goarch` and `goos`? 
Something like ``this.compilerProps(`compiler.${this.compiler.id}.java_home`);``, with java_home being defined in the `*.properties` files?

2021-05-18 09:02 UTC, supergrecko commented
I believe calling compilerProps with 'java_home' when there's a java_home entry present should suffice.

2021-05-19 13:34 UTC, DanielBelow commented
The way I understood the discussion was that a per-compiler solution was best.
Can we have per-compiler `JAVA_HOME`s, if we query for `java_home` (without compiler-id) here?

I had something like this in mind:
```
getDefaultExecOptions() {
    const execOptions = super.getDefaultExecOptions();
    const javaHome = this.compilerProps(`compiler.${this.compiler.id}.java_home`);
    if (javaHome) {
        execOptions.env.JAVA_HOME = javaHome;
    }

    return execOptions;
}
```
so that kotlin-jvm v1.4.3 could have a different java home from kotlin-jvm v1.5, but maybe I misunderstand how `compilerProps` queries the info?

2021-05-19 13:41 UTC, partouf commented
> The way I understood the discussion was that a per-compiler solution was best.
> Can we have per-compiler `JAVA_HOME`s, if we query for `java_home` (without compiler-id) here?
> 
> I had something like this in mind:
> 
> ```
> getDefaultExecOptions() {
>     const execOptions = super.getDefaultExecOptions();
>     const javaHome = this.compilerProps(`compiler.${this.compiler.id}.java_home`);
>     if (javaHome) {
>         execOptions.env.JAVA_HOME = javaHome;
>     }
> 
>     return execOptions;
> }
> ```
> 
> so that kotlin-jvm v1.4.3 could have a different java home from kotlin-jvm v1.5, but maybe I misunderstand how `compilerProps` queries the info?

This is in principle correct, but I would move the `const javaHome = this.compilerProps(`compiler.${this.compiler.id}.java_home`);` thing to here https://github.com/compiler-explorer/compiler-explorer/blob/main/lib/compiler-finder.js#L249

That way you don't have to query the props every compilation request, and can ask for `this.compiler.javaHome` in `getDefaultExecOptions()`

2021-05-20 03:04 UTC, partouf commented
Can you also add the java_home properties to the amazon.properties? You can see where they are installed in the java amazon prop file

2021-06-01 17:30 UTC, partouf commented
I think this is at a stage where its good to go on testing on the real thing. I believe I have installed Kotlin a while ago already.

I will work on it tomorrow probably.

2021-06-02 20:58 UTC, merged

2021-06-02 21:10 UTC, partouf commented
Testing on https://godbolt.org/staging  - seems we forgot about a language thing, will try to remember.. and fix

2021-06-02 22:14 UTC, partouf commented
@DanielBelow @supergrecko 

https://godbolt.org/staging/

Kotlin compilers working:

- 1.4.0
- 1.4.10
- 1.5.0

Not working:

- 1.4.20
- 1.4.21
- 1.4.30
- 1.4.31
- 1.4.32


Ideas?