Ghidra decompiler
compiler-explorer/compiler-explorer pull request #2705
Opened 2021-06-05 01:55 UTC by nimashoghi

2021-06-09 22:44 UTC, mattgodbolt commented
Thanks for this! Will take a look in a while: sorry it's already been 5 days. (I'm on vacation for another week or so, but maybe someone else can take a look too)

2021-07-06 03:25 UTC, RubenRBS requested changes
Sorry about the radio silence

2021-07-06 03:25 UTC, RubenRBS commented on lib/tooling/_all.js
> +export { x86to6502Tool } from './x86to6502-tool';
```suggestion
export { x86to6502Tool } from './x86to6502-tool';

```

2021-07-06 03:25 UTC, RubenRBS commented on lib/tooling/ghidra.js
> +// Copyright (c) 2020, Compiler Explorer Authors
```suggestion
// Copyright (c) 2021, Compiler Explorer Authors
```

2021-07-06 03:25 UTC, RubenRBS commented on lib/tooling/ghidra.js
> +// import {spawn} from "child_process"
```suggestion
```

2021-07-06 03:25 UTC, RubenRBS commented on lib/tooling/ghidra.js
> +//     })
```suggestion
```

2021-07-06 03:25 UTC, RubenRBS commented on lib/tooling/ghidra.js
> +        // )
```suggestion
```

2021-07-06 12:57 UTC, mattgodbolt commented
This looks like a great start, but as @RubenRBS has pointed out there's a few minor things to look at. From the amount of commented-out code it seems incomplete? Is this the case? Is there anything we need to know about to get this merged in, known limitations or similar?

2021-07-06 15:02 UTC, nimashoghi commented
First of all, thanks for the review @RubenRBS! I appreciate the comments.

@mattgodbolt, yes, you are correct that this implementation is incomplete and needs to be adjusted.

My primary limitation in implementing this is my lack of experience with the compiler explorer codebase, but with the implementation I have committed, the limitations are:

1. Ghidra's decompiler must be installed beforehands.
2. Ghidra's decompiler needs SLEIGH (instruction set description) files that need to be downloaded, and the SLEIGHHOME environment variable must point to this installation path.
3. The decompiler tooling only works on binary outputs.
4. Compiler explorer's built-in name demangling must be disabled. This means that Ghidra's output will also have demangled names.


My remaining tasks on this were:

1. Figuring out how Compiler Explorer installs these different applications and making sure Ghidra's decompiler is installed properly. This would also involve making sure that Ghidra has the right SLEIGH (instruction set descriptions) installed for the instruction sets that it would be used on. This is due to limitations # 1 and # 2 above.
2. (Less important) Using c++filt to demangle Ghidra's output symbols for functions. This is due to limitation # 4 described above. The commented code was for this demangler. I wanted to put behind some sort of a flag/setting, but I did not have the time to figure out how this is done with the Compiler Explorer's tooling API.

Finally, I have been a bit busy the past two weeks, but I will review these tasks, as well as @RubenRBS' comments and will push my changes accordingly. Please let me know if you have any comments or suggestions.

2021-07-06 17:25 UTC, mattgodbolt commented
Thanks @nimashoghi ! That's great. We can definitely help with 1. and 2. - there is a separate repo for installation and set up of apps etc. 3. is a bit of an issue but we have a number of tools that mandate "binary only", so it wouldn't be the first. 4. is something we can work on.

Thank you! We're here to help when you have time.

2021-07-19 20:56 UTC, nimashoghi commented
Ok, I have updated my code, which takes care of limitation #4.

I have also created [a PR in the misc-builder repository](https://github.com/compiler-explorer/misc-builder/pull/11) which takes care of limitations #1 and #2.

Feel free to review everything and provide any feedback that you have.

2022-08-15 23:18 UTC, mattgodbolt commented
We seem to have stalled on this. I would like to get support but with https://dogbolt.org/ around I wonder if the need has reduced? I mean, taking source and compiling then decompiling is still valuable, which dogbolt doesn't do... so ... maybe still worth looking in to.

2022-09-26 01:14 UTC, mattgodbolt commented
Ok - I would love to have this but I'm going to close this. I'd be delighted to reopen. Ghidfra would be great, but this PR is a long way behind main these days, and we're moving more and more to typescript, which will make things worse.

2022-09-26 01:14 UTC, closed without merging