Add Thrust/CUB 1.12.1 and 1.13.0.
compiler-explorer/compiler-explorer pull request #2747
Opened 2021-06-28 21:44 UTC by allisonvacanti

Adding new versions of these CUDA libraries. See also compiler-explorer/infra#538

2021-06-29 07:40 UTC, partouf commented
The new versions should be added to https://github.com/compiler-explorer/compiler-explorer/pull/2747/files#diff-b7344ac590742f9fcdee51b23c97652bbb31c63b1ef2fc02df4d4dd186659a95R111

2021-06-29 07:41 UTC, partouf requested changes

2021-06-29 07:41 UTC, partouf commented on etc/config/cuda.amazon.properties
> +libs.thrustcub.versions.112000.version=1.12.1
version id should probably be 112100?

2021-06-29 07:41 UTC, partouf commented on etc/config/cuda.amazon.properties
> +libs.thrustcub.versions.112000.version=1.13.0
version id should probably be 113000

2021-06-30 13:37 UTC, allisonvacanti commented
D'oh -- should be all set now.

2021-06-30 13:44 UTC, merged