Add support for generating SPIR-V assembly from OpenCL C and C++ for OpenCL
compiler-explorer/compiler-explorer pull request #2940
Opened 2021-09-16 09:40 UTC by jzzheng22

Closes #2743.

This PR requires https://github.com/compiler-explorer/infra/pull/590.

2021-09-26 15:11 UTC, partouf requested changes

2021-09-26 15:36 UTC, jzzheng22 commented on lib/compilers/spirv.js
> +        this.disassemblerPath = '/opt/compiler-explorer/SPIRV-Tools-master/build/tools/spirv-dis';
Thanks!

2021-09-26 15:39 UTC, partouf approved these changes

2021-09-28 02:21 UTC, mattgodbolt commented
Oh my! I realise I hadn't pressed "send" on my review, but like a mind-reader @partouf you have done them all :)

2021-10-05 02:42 UTC, mattgodbolt commented
Happy to merge this! Sorry it took so long!

2021-10-05 02:43 UTC, merged

2021-10-05 05:07 UTC, mattgodbolt commented
This is now live, thank you!