Move static/settings.js to TypeScript
compiler-explorer/compiler-explorer pull request #3297
Opened 2022-01-27 08:53 UTC by RubenRBS

This translates the settings file to TS

2022-01-27 10:26 UTC, matsjla requested changes
Looks good overall! I've suggested a couple typescript types that could be added and some other shortcuts, but I'm also happy with it as-is.

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +import $ from 'jquery';
jQuery is globally injected so we can drop this import

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +    }
Can use the data object shorthand

```suggestion
    constructor(public elem: JQuery, public name: string) {}
```

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +    constructor(elem, name, populate) {
Can add types to the constructor arguments

```suggestion
    // TODO: add a better type for populate argument
    constructor(elem: JQuery, name: string, populate: any[]) {
```

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +    constructor(elem, name, sliderSettings) {
Could type arguments as

```suggestion
    constructor(elem: JQuery, name: string, sliderSettings: Record<'max' | 'min' | 'step', number>) {
```

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +    constructor(elem, name, params) {
Could type arguments as

```suggestion
    constructor(elem: JQuery, name: string, params: Record<'min' | 'max', number>) {
```

2022-01-27 10:26 UTC, matsjla commented on static/settings.ts
> +    var currentSettings = settings;
Can replace all instances of var with let/const

2022-01-27 17:20 UTC, matsjla commented on static/settings.ts
> +class ISetting {
BaseSetting might work

2022-01-28 12:39 UTC, matsjla approved these changes

2022-01-28 12:39 UTC, matsjla commented on static/settings.ts
> +        const checkboxes: [string, keyof SiteSettings, boolean][]= [
Could be nice to have a comment here saying what each array member is, maybe
```suggestion
        // Known checkbox options in order [selector, key, defaultValue]
        const checkboxes: [string, keyof SiteSettings, boolean][]= [
```

2022-01-29 01:00 UTC, merged

2022-01-29 22:50 UTC, partouf commented
this is now live