Add Dart support
compiler-explorer/compiler-explorer pull request #3352
Opened 2022-02-10 16:39 UTC by miDeb

Closes #3099

This adds support for running the dart compiler (it was already installed since https://github.com/compiler-explorer/infra/pull/627). For now this means it supports dart version 2.14.4 (newest version would be 2.16). I hope those changes make sense, but it's likely I've missed something :)

2022-02-10 16:48 UTC, partouf requested changes
Thanks for doing this!
I think you'll have to override the parser functions in `asm-parser-dart` instead of changing `asm-parser`, this breaks too much as far as I can see

2022-02-10 16:48 UTC, partouf commented on lib/asm-parser.js
> +                source = null;
This is not correct for most compilers and assembly. Perhaps overriding this class and function would be better than to cause bugs with this.

2022-02-10 16:48 UTC, partouf commented on lib/asm-parser.js
> +            if (isMainsource) {
this also looks like a breaking change

2022-02-10 16:57 UTC, miDeb commented
Thanks for the quick review! I moved my changes to `asm-parser-dart.js` and removed them from `asm-parser.js`.

2022-02-10 17:03 UTC, partouf approved these changes
Thanks for the quick changes. Looks good to me

2022-02-11 15:19 UTC, merged

2022-02-11 15:32 UTC, partouf commented
I have disabled execution for now, it looks like it didn't actually create an executable (and didn't have +x), probably just an object file

```
$ readelf -h output.s
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          894448 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         6
  Size of section headers:           64 (bytes)
  Number of section headers:         15
  Section header string table index: 9
```

2022-02-11 15:49 UTC, miDeb commented
Sorry, I forgot to copy the execution wrapper to the actual config file. It created an "aot snapshot" which should be executed with `dartaotruntime`.

2022-02-11 15:59 UTC, miDeb commented
I opened #3357 to (hopefully) fix it.

2022-02-12 00:07 UTC, fzyzcjy commented
Wow thanks for handling dart support!