Pane renaming saves state to local storage now
compiler-explorer/compiler-explorer pull request #3364
Opened 2022-02-13 12:53 UTC by dead-tech

Now changes made to pane names are saved to local storage, and should be working as expected.

Note  (See #3323):
 - Renaming for editor is still disabled at the moment
 - `Alert` still isn't a singletone.

2022-02-13 18:49 UTC, RubenRBS requested changes
Looking good. Thanks for taking the time to fix the issues found with the initial version :)

Even though it's currently disabled, can you update `Editor.prototype.updateTitle` to check for `'CMakeLists.txt'` always in the result from `getPaneName` and not the custom name even if it has one please?

2022-02-13 18:49 UTC, RubenRBS commented on static/pane-renaming.ts
> +        this.alertSystem = new Alert();
What you can do here about the alerty situation is to use the alert coming from the parent Pane (In most panes, it's the `this.alertSystem variable`) So something like this

```suggestion
    constructor(pane: any, state: any, alertSystem?: Alert) {
        super();
        this.pane = pane;
        if (alertSystem === undefined) {
            this.alertSystem = new Alert();
        } else {
            this.alertSystem = alertSystem;
        }
```

2022-02-13 19:27 UTC, dead-tech commented on static/pane-renaming.ts
>  import $ from 'jquery';
Good to know 😄

2022-02-13 19:31 UTC, dead-tech commented on static/panes/ast-view.js
> +    this.paneRenaming.on('renamePane', this.updateState.bind(this));
So I guess it's fine if I leave them as they are.

2022-02-13 19:32 UTC, dead-tech commented on static/panes/cfg-view.interfaces.ts
> +    componentName: string;
My bad, it was something that had to do with the local storage version of the feature. Removed it!

2022-02-13 19:35 UTC, dead-tech commented on static/panes/pp-view.ts
> +        this.container.setTitle(_.escape(name));
Yeah, they're identical, removed the overridden one.

2022-02-14 14:33 UTC, dead-tech commented
> Looking good. Thanks for taking the time to fix the issues found with the initial version :)
> 
> Even though it's currently disabled, can you update `Editor.prototype.updateTitle` to check for `'CMakeLists.txt'` always in the result from `getPaneName` and not the custom name even if it has one please?

@RubenRBS Is this ([ba7e0b7](https://github.com/compiler-explorer/compiler-explorer/pull/3364/commits/ba7e0b7adec56f284c2cc00f8a3bd0102abb8624)) what you meant?

2022-02-14 16:54 UTC, RubenRBS commented
Yes! Thanks

2022-02-16 14:12 UTC, dead-tech commented
@mattgodbolt on #3360 said this:

> I think it's considered bad form to dynamically add members in this way: this is also a problem when `this.paneName = "";` is equivalent to `this.paneName` was never defined at all (which may be intentional, but again is subtle). I'd prefer I think explicitly initialising it to `null` (or `""` if that makes sense) in the constructor to say "this is at least expected to be here".

So shall I go ahead and define `paneName` and set it to `null` in the constructor of all the panes that expect this property to exist, and not dynamically add this?

Btw as #3360 is waiting for this pr to get merged, I would say, apart from the change above, this might be ready

2022-02-18 06:11 UTC, RubenRBS commented
Hi! Sorry for the review delay. I plan to test this later this evening :)

2022-02-18 09:21 UTC, RubenRBS approved these changes

2022-02-18 09:21 UTC, RubenRBS commented on static/panes/cfg-view.ts
> +const Alert = require('../alert').Alert;
```suggestion
import { Alert } from '../alert';
```

2022-02-18 09:21 UTC, RubenRBS commented on static/panes/pane.interfaces.ts
> +    componentName: string;
Is this still needed?

2022-02-18 15:42 UTC, dead-tech commented on static/panes/pane.interfaces.ts
> +    componentName: string;
Nope, my bad

2022-02-21 23:07 UTC, RubenRBS commented
Sorry that this took so long to get reviewed again, life got busy.
Thank you so much for taking the time to implement this feature and again, sorry about all the delays along the way :)

2022-02-21 23:07 UTC, merged

2022-02-27 18:24 UTC, mattgodbolt commented
This is now live! Yay!