Add HDF5 and HighFive libraries to amazon config
compiler-explorer/compiler-explorer pull request #3479
Opened 2022-03-31 21:47 UTC by ohm314

This updates the configuration to add both HDF5 (1.12.1, 1.13.1) and
HighFive to the libraries available in CE. Since HDF5 is a shared object
library, these changes should go along with changes in infra.

See also PR here: https://github.com/compiler-explorer/infra/pull/695

The main question that is still open is how the paths should be exactly set. For the local setup I have verified that in principle all components play long well. But adjusting the paths for the `/opt/compiler-explorer` tree on the AWS instances I am flying blind.

More specifically:
- How do we deal with multiple libhdf5.so (coming from multiple library versions?)
- The headers had to be installed with a `post_stage` script (in the infra config), but I am not entirely sure where they actually end up?

2022-04-01 09:36 UTC, RubenRBS requested changes

2022-04-01 09:36 UTC, RubenRBS commented on etc/config/c++.amazon.properties
> +libs.highfive.name=HighFive
This should go before highway

2022-04-04 13:28 UTC, ohm314 commented on etc/config/c++.amazon.properties
> +libs.highfive.name=HighFive
oops :)

2022-04-05 02:39 UTC, mattgodbolt approved these changes
LGTM! will merge and we can see how it works out :-)

We _may_ have to revert the command-line order change and come up with another solution though as it had some unfortunate side effects. We can discuss but I have some ideas!

2022-04-05 02:40 UTC, merged

2022-04-05 03:29 UTC, mattgodbolt commented
This is rolling out to prod now - I'm heading to bed shortly after but we can liaise tomorrow and work out where this stands :) I didn't have to revert (yet!) and I think I've _maybe_ got a solution...