add(support): toit programming language
compiler-explorer/compiler-explorer pull request #3661
Opened 2022-05-14 16:04 UTC by snxx-lppxx

2022-05-14 18:06 UTC, RubenRBS requested changes
Hi! Thanks for this :) I have some requests and questions, but overall looks great

2022-05-14 18:06 UTC, RubenRBS commented on etc/config/toit.defaults.properties
> +compilers=/usr/bin/toit
Is this meant to be also live in the site? if so, it's missing some things:
- A PR in the sister repo https://github.com/compiler-explorer/infra that installs the compiler to the required places (There are some example PRs you can check out)
- And a `toit.amazon.properties` files to configure the compilers for the live site

Also, you should add the language to `.github/labeler.yml`

2022-05-14 20:51 UTC, RubenRBS commented on lib/compilers/toit.js
> +/**
Also, before I forget. We're trying to slowly move towards typescript, so we would appreciate if any new files could be written in TS, which _should_ be easy enough, but do let us know if you have any questions regarding that :)

2022-05-20 11:46 UTC, partouf requested changes

2022-05-20 11:46 UTC, partouf commented on etc/config/toit.amazon.properties
> +compiler.toit161.exe=/opt/compiler-explorer/toit-1.6/bin/toit
the executable is installed with the name `toit.run`

2022-05-20 11:48 UTC, partouf commented
Sidenote; you can add your original Megagreater example to the folder `examples/toit` so that it can be loaded in by users

2022-06-24 20:07 UTC, closed without merging

2022-06-24 20:34 UTC, partouf commented
Thanks for the addition. I have disabled Toit for the live website as there is no way to show assembly or IR atm, but it's available for users that run a local installation, as long as they select "Execute the code"