Port lib/formatters to TypeScript
compiler-explorer/compiler-explorer pull request #3741
Opened 2022-05-31 14:58 UTC by matsjla

Also updates relevant documentation

2022-05-31 15:35 UTC, partouf requested changes

2022-05-31 15:35 UTC, partouf commented on lib/formatters/base.ts
> +export type ExecResult = {
You can use https://github.com/compiler-explorer/compiler-explorer/blob/main/types/execution/execution.interfaces.ts#L3

2022-05-31 20:15 UTC, RubenRBS commented on lib/formatters/base.interfaces.ts
> +export interface FormatOptions {
Can you make this a `type`? We discussed making data structs types to better differenciate them

2022-06-04 15:40 UTC, partouf approved these changes

2022-06-05 14:09 UTC, merged