Add the gitlab bmulti library
compiler-explorer/compiler-explorer pull request #3752
Opened 2022-06-06 07:24 UTC by correaa

Proposing to add the B-Multi library to the live site. https://gitlab.com/correaa/boost-multi

Followed the steps as best as I could in https://github.com/compiler-explorer/compiler-explorer/blob/main/docs/AddingALibrary.md#adding-a-new-library-to-the-live-site

Feedback on improving the hooks and the organizations of files in the repository is welcome.
The goal is to include the library by doing `#include<multi/array.hpp>`.

This PR is related to infra's PR https://github.com/compiler-explorer/infra/pull/745

2022-06-06 14:11 UTC, mattgodbolt requested changes
these need to be `.path=<path>` and `.version=<name of version to show user>` Thanks!

2022-06-06 14:11 UTC, mattgodbolt commented on etc/config/c++.amazon.properties
> +libs.bmulti.versions.trunk=/opt/compiler-explorer/libs/boost-multi/include
```suggestion
libs.bmulti.versions.trunk.version=trunk
libs.bmulti.versions.trunk.path=/opt/compiler-explorer/libs/boost-multi/include
```

2022-06-06 17:59 UTC, mattgodbolt approved these changes

2022-06-06 17:59 UTC, mattgodbolt commented
Thanks! I'll do a site update tonight to pick this up :)

2022-06-06 18:00 UTC, merged

2022-06-06 18:03 UTC, correaa commented
This is very exciting. Thank you.

Once all works I will step up to the next level and add it to the CUDA.godbolt if you agree. 
The library supports CUDA memory as well (https://gitlab.com/correaa/boost-multi#cuda-thrust)

2022-06-07 02:08 UTC, mattgodbolt commented
This is now live!

2022-06-07 02:36 UTC, correaa commented
Awesome.

How do I include it? If I put `#include<multi/array.hpp>` I get "fatal error: 'multi/array.hpp' file not found".

https://godbolt.org/z/qo4n3bedE

2022-06-07 02:37 UTC, correaa commented
I might add it for Circle later as well (I made the library compatible with Circle recently, after some work).

2022-06-08 05:21 UTC, correaa commented
Works now, thank you. How often does godbolt pulls the library from master? nightly I assume given the name of the keyword.

2025-08-20 07:53 UTC, correaa commented
I noticed that MSVC compilers that used to be described with "WINE" now say "ex-WINE", and most libraries are not available for it anymore. What would be the correct way to integrate a header library, like this one, into these ex-WINE compilers?