Move cursor to the right position when clicking on a tag in tool outputs
compiler-explorer/compiler-explorer pull request #3843
Opened 2022-07-06 09:24 UTC by frederic-tingaud-sonarsource

When there is a line and column number in the outputs of a tool, CE automatically changes it to a link that will highlight the location in the editor when hovered and scroll the editor when clicked. I have the feeling users expect the cursor to move to this position when clicking (that was my case, so 100% of the data points I have agree with myself).

2022-07-06 09:53 UTC, partouf commented
Hmm, I don’t know about this one. Think this can cause a bunch of issues, especially when you just accidentally moved your mouse over something and poof things scroll all over the place..

2022-07-06 09:54 UTC, frederic-tingaud-sonarsource commented
The cursor move is done only on click, not on hover.

2022-07-06 09:56 UTC, partouf commented
> The cursor move is done only on click, not on hover.

Ahh ok

2022-07-10 16:18 UTC, RubenRBS requested changes
Hi! Thanks for this (And the rest of the PRs you've submited too), it looks good!

Can you modify [static/event-map.ts#L63](https://github.com/compiler-explorer/compiler-explorer/blob/main/static/event-map.ts#L63) to reflect the new change? The panes will complain after they are ported to ts otherwise

2022-07-12 20:58 UTC, matsjla commented
I'm not too sure what implications this change has, I haven't worked too much with the tools. Would anyone be able to update me? @partouf

2022-07-14 21:15 UTC, RubenRBS commented
This code gets executed as part of the linked line event. (ie: the compiler asking the editor to highlight the sourceline an asm instruction comes from). It has a parameter to force the views to scroll to that line. This change also moves the cursor to that position, as before we just let it stay.

I know Partouf wanted to refactor some of this funcitonality at some point

2022-07-15 18:01 UTC, matsjla approved these changes
Cool stuff, looks nice - just need to update the EventMap as Ruben mentioned!

2022-07-18 16:39 UTC, merged