Repair http(s) includes after formatting
compiler-explorer/compiler-explorer pull request #3924
Opened 2022-07-28 18:08 UTC by falbrechtskirchinger

clang-format inserts spaces after the URI scheme and before the hier-part. Remove the spaces to reform a valid URL.

For example, formatting the following code
```cpp
#include <https://localhost:8443/develop/json.hpp>
```
results in a broken https include:
```cpp
#include <https:  //localhost:8443/develop/json.hpp>
```

This could of course be done on the client side but might be a little messy. Let me know if that's preferable.

2022-07-28 21:32 UTC, partouf commented
Fixes https://github.com/compiler-explorer/compiler-explorer/issues/2928

I think this is an Ok solution to the problem

2022-07-29 09:41 UTC, matsjla requested changes
I'm also fine with this fix.

I would however, want to replace the .then() into new Promise() chain with await. I've added a suggestion below. Otherwise LGTM! Thanks

2022-07-29 09:41 UTC, matsjla commented on lib/formatters/clang-format.ts
> +            return new Promise((resolve, _reject) => resolve(result));
```suggestion
        const result = await exec.execute(this.formatterInfo.exe, [`--style=${arg}`], {input: source});
        if (result.code === 0) {
            // Repair http(s) includes, i.e., remove the spaces inserted before the hier-part of the URI
            const includeFind = /^(\s*#\s*include\s*["<]https?:)\s+(\/\/[^">]+[">].*)/;
            const includeReplacement = '$1$2';
            const lines = result.stdout.split('\n');
            for (const idx in lines) lines[idx] = lines[idx].replace(includeFind, includeReplacement);
            result.stdout = lines.join('\n');
        }
        return result;
```

2022-07-29 11:46 UTC, matsjla approved these changes
LGTM Thanks!

2022-07-29 13:52 UTC, merged

2022-08-03 21:08 UTC, mattgodbolt commented
Thanks: this is now live!