Update to EVE support
compiler-explorer/compiler-explorer pull request #4111
Opened 2022-10-04 16:02 UTC by jfalcou

2022-10-05 07:39 UTC, RubenRBS commented
👍

2022-10-05 07:39 UTC, RubenRBS requested changes

2022-10-05 07:39 UTC, RubenRBS commented on etc/config/c++.amazon.properties
> +libs.eve.versions.v2022030.path=/opt/compiler-explorer/libs/eve/v2022.09.0/include
Wrong version key, should be `v2022090`

2022-10-05 07:39 UTC, RubenRBS commented on etc/config/circle.amazon.properties
> +libs.eve.versions.v2022030.version=v2022090
Wrong version key, should be `v2022090`

2022-10-05 07:51 UTC, jfalcou commented on etc/config/circle.amazon.properties
> +libs.eve.versions.v2022030.version=v2022090
will fix, feel stupid XD

2022-10-07 05:35 UTC, RubenRBS commented on etc/config/circle.amazon.properties
> +libs.eve.versions.v2022030.version=v2022090
😄

2022-10-07 05:35 UTC, merged