Add Josuttis' Belle Views to C++ compiler
compiler-explorer/compiler-explorer pull request #4452
Opened 2022-12-18 03:39 UTC by correaa

https://github.com/josuttis/belleviews/tree/main/sources

2022-12-18 16:51 UTC, RubenRBS approved these changes
Thanks!

2022-12-18 16:51 UTC, RubenRBS commented on etc/config/c++.amazon.properties
> +libs.belleviews.versions.trunk.path=/opt/compiler-explorer/libs/belleviews/sources
I think the final path is
```suggestion
libs.belleviews.versions.trunk.path=/opt/compiler-explorer/libs/belleviews/trunk/sources
```

2022-12-18 19:58 UTC, RubenRBS requested changes
Meant to request changes instead of accepting

2022-12-18 20:17 UTC, correaa commented
> Meant to request changes instead of acepting

I agree with the change.

2022-12-18 21:40 UTC, RubenRBS approved these changes

2022-12-18 21:49 UTC, merged

2022-12-18 21:55 UTC, correaa commented
thanks. good day today🇦🇷.

2022-12-19 02:04 UTC, jeremy-rifkin commented
This is now live

2022-12-19 17:57 UTC, correaa commented
And it works now: https://godbolt.org/z/dqboqEbfh.

@josuttis