tools: update GitHub Actions workflows
compiler-explorer/compiler-explorer pull request #4943
Opened 2023-04-04 22:00 UTC by VoltrexKeyva

- Update the actions in the GitHub Actions workflows to their latest versions.
- Run the workflows on the latest versions of the platforms where appropriate.
- Set the `check-latest` field of the `actions/setup-node` action to `true` to use the latest release of the specified Node.js version instead of using the cached one when there's a new release available.
- Explicitly specify the action versions instead of using the `latest` tag.

2023-04-04 22:09 UTC, partouf commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
this must stay 20.04 to remain compatible with our production environment

2023-04-04 22:11 UTC, mattgodbolt requested changes
Thanks so much! It's definitely been on the todo list to look at this.

Out of an abundance of caution, as our nodes currently run on 20.04 (stuck there currently due to some `nsjail` issues, along with some other things), I'd like to leave the build/deploy step on 20.04. I don't _think_ there's any way binary executable artifacts get into the deploy BUT I'd rather do the uncontroversial changes in one PR, and the other separately where we can more targetedly test it.

2023-04-04 22:11 UTC, mattgodbolt commented on .github/workflows/deploy-win.yml
> -    runs-on: windows-2019
@partouf do you think this is ok?

2023-04-04 22:11 UTC, mattgodbolt commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
For these we are currently actually deploying on ubuntu-20.04 so we cannot update these without further checking to ensure the built distribution doesn't (somehow) have some tendrils from 22.04 in it.

2023-04-04 22:11 UTC, mattgodbolt commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
ditto

2023-04-04 22:11 UTC, mattgodbolt commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
ditto. We can investigate our options here and do a test to our staging environment. Can you make a separate PR with these changes, please?

2023-04-04 22:11 UTC, partouf commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
because this is still using npm to run some sentry commands, it might be better for this to remain 20.04 for now

2023-04-04 22:12 UTC, VoltrexKeyva commented on .github/workflows/test-and-deploy.yml
> +    runs-on: ubuntu-latest
Should it stay as 20.04 only in this file for the two lines you just commented on or on all files?

2023-04-04 22:12 UTC, partouf commented on .github/workflows/test-frontend.yml
> +    runs-on: ubuntu-latest
best this stays 20.04 to remain compatible with our production environment and get more reliable tests

2023-04-04 22:13 UTC, partouf commented on .github/workflows/test-win.yml
> +    runs-on: windows-latest
this must stay windows-2019 to remain compatible with our production environment

2023-04-04 22:14 UTC, partouf commented on .github/workflows/deploy-win.yml
> +    runs-on: windows-latest
this must stay windows-2019 to remain compatible with our production environment

2023-04-04 22:16 UTC, partouf commented on .github/workflows/deploy-win.yml
> -    runs-on: windows-2019
nope, just left similar comments

2023-04-05 16:15 UTC, mattgodbolt approved these changes
Looks good to me. Will merge in a bit :) Thanks for this!

2023-04-05 16:24 UTC, merged