Updated java toolchain
compiler-explorer/compiler-explorer pull request #6345
Opened 2024-04-11 15:33 UTC by fbarbari

This PR references [this issue](https://github.com/compiler-explorer/compiler-explorer/issues/6289) and [this PR](https://github.com/compiler-explorer/infra/pull/1272).

New Java versions (and corresponding groups):
 - 8u402b06
 - 9.0.4
 - 10.0.2
 - 22.0.0

Updated Java versions:
 - 12.0.1 -> 12.0.2
 - 17.0.0 -> 17.0.2
 - 18.0.0 -> 18.0.2
 - 20.0.0 -> 20.0.2
 - 21.0.0 -> 21.0.2

Also updated the default java version to 21.0.2

2024-04-12 11:49 UTC, junlarsen requested changes
Thanks for updating them! I believe the best thing to do here is to add the new compilers in addition to the old ones, otherwise we break backwards compatability

2024-04-12 11:49 UTC, junlarsen commented on etc/config/java.amazon.properties
> +group.java12.compilers=java1202
I believe you should add 1202 in additon to 1201 here (and consequently for the other versions too). Any shortlinks using 1201 will break if we remove the old compiler ids.

2024-04-15 09:39 UTC, junlarsen approved these changes
This looks good now, thanks a lot!

2024-04-22 16:39 UTC, merged

2024-04-22 18:47 UTC, partouf commented
this is now live