Add Flang frontend driver to Fortran Compilers
compiler-explorer/compiler-explorer pull request #6419
Opened 2024-05-01 10:47 UTC by harishch4

"This pull request introduces the Flang frontend driver as a new compiler, as discussed in issue #6400. with minimal support. 

With this change, users can now specify LLVM Flang frontend-related options such as _**-emit-hlfir, -fdebug-dump-parse-tree**_, etc.,(no explicit **_-fc1_** needed) by selecting the compiler (**flang-trunk-fc1**)."

2024-05-02 13:27 UTC, dkm requested changes

2024-05-02 13:27 UTC, dkm commented on etc/config/fortran.amazon.properties
> +group.clang_llvmflang.compilers=flangtrunk:flangtrunknew:flangtruncknew-fc
Should be `trunknew-fc`. There's an extra `c` here

2024-05-02 13:27 UTC, dkm commented on etc/config/fortran.amazon.properties
> +compiler.flangtruncknew-fc.supportsBinaryExecute=false
same type in trunk

2024-05-02 22:14 UTC, partouf approved these changes
Thank you for this! this is excellent work

2024-05-10 18:47 UTC, merged

2024-05-14 04:08 UTC, mattgodbolt commented
I tested this in staging and without really understanding what's going on, it doesn't error but doesn't really seem to do anything. Will be pushed live shortly.

2024-05-14 04:09 UTC, partouf commented
`-emit-hlfir` seems to work

2024-05-14 04:13 UTC, mattgodbolt commented
ok; this is rolling out now (ETA 15m)