Remove dependency on `request` and replace it with `node-fetch`
compiler-explorer/compiler-explorer pull request #6800
Opened 2024-08-26 22:26 UTC by detjonmataj

2024-08-28 19:59 UTC, junlarsen requested changes
Any reason we can't use Node's builtin fetch?

2024-08-28 20:12 UTC, detjonmataj commented
@junlarsen I wasn't aware that node has a stable build in fetch that is already polyfilled. I can easily switch to that. Let me know what you think.

2024-08-28 20:21 UTC, detjonmataj commented
+ Not sure which version of node you use in prod, so this might be a problem
![image](https://github.com/user-attachments/assets/52c6ffbd-09e3-4dc9-89c3-59e24fe219a5)

2024-08-28 20:24 UTC, partouf commented
> + Not sure which version of node you use in prod, so this might be a problem ![image](https://private-user-images.githubusercontent.com/84277348/362440804-52c6ffbd-09e3-4dc9-89c3-59e24fe219a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzY4NDcsIm5iZiI6MTcyNDg3NjU0NywicGF0aCI6Ii84NDI3NzM0OC8zNjI0NDA4MDQtNTJjNmZmYmQtMDllMy00ZGM5LTg5YzMtNTllMjRmZTIxOWE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDIwMjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZTg0M2QwNDQ4NTg0ODRhZGYwOWRlYzNiM2ZhZWEyM2U2YzkzYjNmZDhlY2IxY2IxZDFjODEyNGI0N2I1NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vauUCJE-4zqxoGf8JWFXgPsJEeciFwdeDqpcP3uZXqE)

In prod we use currently: v20.15.0
And we're "trying" to stay compatible with v18.14.1

2024-08-29 09:07 UTC, OfekShilon commented
@mattgodbolt  perhaps we can deploy to staging for a short while?

2024-08-29 11:50 UTC, detjonmataj commented
> @mattgodbolt perhaps we can deploy to staging for a short while?

Sure, once I test `lib/storage/remote.ts` and use node's built in fetch it should be ready for deployment.

> Any reason we can't use Node's builtin fetch?

To use node's built in fetch I just had to remove `node-fetch` module so the app uses the global builtin `fetch`. It was trivial for the most part due to the matching interfaces, however one issue I noticed was on `lib/buildenvsetup/ceconan.ts:197` where the package from ce conan's response body is piped to gunzip (then it is piped to extract, seems like an use-case for using stream pipelines).  It appears that the node's built in fetch maintains the same API as the browser's fetch thus there are incompatibilities between streams. I have several solutions to overcome this issue and for the most part I think it all comes to aesthetics rather than the right  or the wrong way of mapping the streams .

1. Loop the response body bytes and write them to `gunzip`.

```js
const reader = res.body.getReader();
let isDone = false;

while (!isDone) {
    const {done, value} = await reader.read();
    isDone = done;
    if (value) gunzip.write(value);
}

gunzip.end();
```

2. Wrap gunzip's writable stream with browser's WrittableStream:

```js
const gunzipWrapper = new WritableStream<Uint8Array>({
write(chunk) {
    gunzip.write(chunk);
},
close() {
    gunzip.end();
},
});

await res.body.pipeTo(gunzipWrapper);
```

3. Wrap fetch readable stream (browser's) with node's RedableStream:

```js
const reader = res.body.getReader();
const responseBodyAsNodeStream = new Readable({
    async read() {
        const {done, value} = await reader.read();
        this.push(done ? null : Buffer.from(value));
    },
});

responseBodyAsNodeStream.pipe(gunzip);
```

Additionally, I would like to improve the code and error handling because currently it feels a bit hacky, however, first, I would like to make sure that it is working correctly and cover some of the test before making more changes. Let me know your thoughts.

As a side note for me, the user should see proper error messages instead of unhanded exception's traces.

2024-08-29 18:11 UTC, detjonmataj commented
Thanks for the feedback! I decided to go with the 3rd solution because it seems like a safer option. Piping directly from a readable stream to a writable stream allows Node.js to handle these operations under the hood by managing backpressure automatically... The pipe method will handle calling the read and write methods as needed, so I believe that it won't cause any issue. Also, it shouldn't matter that the response body stream is read manually.

In contrast, the 2nd solution pipes data to a writable stream, which then manually writes to the gunzip stream. This approach requires you to manually handle backpressure by waiting for the gunzip stream to drain before writing further, as well as manually ending the stream.

As for the failing tests it's obvious that the code requires node 21, though we can suppress the warning.

2024-08-29 22:32 UTC, detjonmataj commented
I'd say it's now ready for testing in either staging or beta site.

2024-10-01 00:59 UTC, mattgodbolt commented
@detjonmataj thanks; I'll try and get a chance to look at this.

2024-10-01 02:31 UTC, mattgodbolt commented
I've updated some tests etc in the linked Draft PR. We'll wait until we're onto node 22 to avoid the linting errors of us using `fetch` here.

2024-10-03 16:23 UTC, detjonmataj commented
Amazing, thanks @mattgodbolt !

2025-01-30 18:21 UTC, mattgodbolt commented
We're slowly getting there. We're in the process of moving to node 22; though we still currently have node 20 support

2025-02-18 19:46 UTC, junlarsen commented
Would this be ready now that #7343 is in @mattgodbolt?

2025-02-18 20:06 UTC, mattgodbolt commented
Sadly not as we need node 22 and we still support node 20 :(

2025-02-26 17:28 UTC, mattgodbolt commented
After discussion with @partouf `fetch` was experimental in v20, so maybe we can mereg this after all. Will need testing and of course bringing up to date.

2025-02-26 23:39 UTC, detjonmataj commented
@mattgodbolt Sure I'll take a look as well. Thanks!

2025-02-28 02:28 UTC, detjonmataj commented
I resolved the conflicts. I’d like to conduct further testing before it’s ready to be merged.

2025-03-15 21:55 UTC, detjonmataj commented
I made some adjustments and ran tests locally. Everything seems to be working correctly, and I think it’s ready for testing on the beta/staging site.

Earlier, we discussed a workaround for converting `ReadableStream` (Web’s Stream API) to `Readable` (Node’s Stream API). Last time, I couldn’t get [`Readable.fromWeb(res.body)`](https://nodejs.org/api/stream.html#streamreadablefromwebreadablestream-options) to work (probably because it's still experimental). But this time, I found that `ReadableStream` [implements the async iterable protocol](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream#async_iteration), which gave me the idea to use [`Readable.from(res.body)`](https://nodejs.org/api/stream.html#streamreadablefromiterable-options) instead. This is a stable feature which constructs `Readable` streams from iterators. The good news is that this official helper method simplifies the process, and we don’t need to worry about handling manually stream's backpressure or anything like that.

Another working solution is to convert the Gunzip writable stream to a Web writable stream using `res.body.pipeTo(Writable.toWeb(gunzip));`. 

Let me know if anything is unclear or if anything else is needed. Thanks!

2025-04-24 23:57 UTC, mattgodbolt commented
Thank you @detjonmataj ! Your patience is legendary: I think I'm finally ready to start some testing on my side.

2025-04-25 17:35 UTC, mattgodbolt commented
I am sorry I clearly confused everything trying to rebase and merge this :(

2025-04-25 17:47 UTC, mattgodbolt commented
Local testing:
- [x] successfully streams to proxied CE instances (e.g. windows prod)
- [ ] resolves (old) short urls
- [ ] ceconan.ts

2025-04-25 17:53 UTC, mattgodbolt commented
This all looks good to me, tested locally :tada:

The fact it's experimental in 20.* doesn't worry me as we are only doing super simple things with it _and_ they're not on any "normal" path for end users.

2025-04-25 17:57 UTC, detjonmataj commented
> Thank you @detjonmataj ! Your patience is legendary: I think I'm finally ready to start some testing on my side.

HAHA, it's okay Matt, I'll be around if you need anything.

I think we need to bring changes you made to `test/google-tests.ts`  in #6924 .

2025-04-25 19:26 UTC, mattgodbolt commented
I _think_ those are in here? Or maybe I'm missing something? I'll double check but if you have a link to the change you mean...

2025-04-25 19:39 UTC, detjonmataj commented
> I _think_ those are in here? Or maybe I'm missing something? I'll double check but if you have a link to the change you mean...

[This](https://github.com/compiler-explorer/compiler-explorer/pull/6924/files#diff-aa18afad3522566c5191a52a8c97a964267ea0a2ef98c9c3bfebfb9e04300fba
) is what I'm referring to

![image](https://github.com/user-attachments/assets/fd76bd55-82e8-4179-b8c1-1670acfa6711)

Looking at the screenshot below current PR contains only this change
![image](https://github.com/user-attachments/assets/aafcaddd-1a0f-4371-9d62-4b21899c896a)

2025-04-26 01:35 UTC, mattgodbolt commented
Thank you again @detjonmataj !

2025-04-26 01:38 UTC, junlarsen approved these changes
Thanks! Legendary patience as @mattgodbolt already pointed out :laughing:

2025-04-26 01:43 UTC, mattgodbolt commented
I'm just comparing my other branch that @detjonmataj linked against this and applying some mostly cosmetic things, then I'll merge :)

2025-04-26 02:00 UTC, mattgodbolt commented
Ok I think we're good now :) And I found a sad but temporary workaround for google shortener links

2025-04-26 02:24 UTC, merged